import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { createStudent } from '@/api/students'
import PageHeader from '@/components/ui/PageHeader'

const EMPTY = {
  email: '', first_name: '', last_name: '', phone: '', password: '',
  date_of_birth: '', gender: '', address: '',
  blood_group: '', guardian_name: '', guardian_phone: '',
}

function buildPassword(firstName, dob) {
  const name = firstName.trim().slice(0, 4)
  if (!name || !dob) return ''
  // dob is yyyy-mm-dd from the date input → reformat to ddmmyyyy
  const [y, m, d] = dob.split('-')
  if (!y || !m || !d) return ''
  return `${name}${d}${m}${y}`
}

export default function StudentForm() {
  const navigate = useNavigate()
  const qc = useQueryClient()
  const [form, setForm] = useState(EMPTY)
  const [errors, setErrors] = useState({})
  const [passwordOverridden, setPasswordOverridden] = useState(false)
  const [showPassword, setShowPassword] = useState(true)

  const createMut = useMutation({
    mutationFn: createStudent,
    onSuccess: (res) => {
      qc.invalidateQueries({ queryKey: ['students'] })
      navigate(`/admin/students/${res.data.id}`)
    },
    onError: (e) => {
      const data = e.response?.data
      if (data && typeof data === 'object') setErrors(data)
      else setErrors({ non_field_errors: ['Something went wrong.'] })
    },
  })

  function set(field, value) {
    setForm((f) => {
      const next = { ...f, [field]: value }
      // Regenerate password atomically whenever name or DOB changes
      if (!passwordOverridden && (field === 'first_name' || field === 'date_of_birth')) {
        next.password = buildPassword(
          field === 'first_name' ? value : f.first_name,
          field === 'date_of_birth' ? value : f.date_of_birth,
        )
      }
      return next
    })
    setErrors((e) => { const next = { ...e }; delete next[field]; return next })
  }

  function handlePasswordChange(value) {
    setPasswordOverridden(true)
    setForm((f) => ({ ...f, password: value }))
    setErrors((e) => { const next = { ...e }; delete next.password; return next })
  }

  function resetPassword() {
    setPasswordOverridden(false)
    setForm((f) => ({ ...f, password: buildPassword(f.first_name, f.date_of_birth) }))
  }

  function handleSubmit(e) {
    e.preventDefault()
    setErrors({})
    createMut.mutate(form)
  }

  const fieldError = (f) => errors[f]?.[0] ?? errors[f]
  const isAutoGenerated = !passwordOverridden && !!form.password

  return (
    <div>
      <PageHeader title="Add New Student" subtitle="Creates a student account and profile" />

      <form onSubmit={handleSubmit} className="bg-white rounded-xl border border-gray-200 p-6 max-w-2xl space-y-6">
        {errors.non_field_errors && (
          <p className="text-sm text-red-600">{errors.non_field_errors[0]}</p>
        )}

        {/* Account */}
        <section>
          <h3 className="text-sm font-semibold text-gray-700 mb-3 pb-1 border-b border-gray-100">Account</h3>
          <div className="grid grid-cols-2 gap-4">
            <Field label="First Name" error={fieldError('first_name')}>
              <input required value={form.first_name} onChange={(e) => set('first_name', e.target.value)}
                className={input(fieldError('first_name'))} placeholder="Jane" />
            </Field>
            <Field label="Last Name" error={fieldError('last_name')}>
              <input required value={form.last_name} onChange={(e) => set('last_name', e.target.value)}
                className={input(fieldError('last_name'))} placeholder="Doe" />
            </Field>
            <Field label="Email" error={fieldError('email')}>
              <input required type="email" value={form.email} onChange={(e) => set('email', e.target.value)}
                className={input(fieldError('email'))} placeholder="jane@school.com" />
            </Field>
            <Field label="Phone" error={fieldError('phone')}>
              <input value={form.phone} onChange={(e) => set('phone', e.target.value)}
                className={input(fieldError('phone'))} placeholder="+91 9876543210" />
            </Field>

            {/* DOB moved here so password auto-generates as you fill the form top-to-bottom */}
            <Field label="Date of Birth" error={fieldError('date_of_birth')}>
              <input type="date" value={form.date_of_birth} onChange={(e) => set('date_of_birth', e.target.value)}
                className={input(fieldError('date_of_birth'))} />
            </Field>

            <Field label="Gender" error={fieldError('gender')}>
              <select value={form.gender} onChange={(e) => set('gender', e.target.value)} className={input(fieldError('gender'))}>
                <option value="">Select</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="other">Other</option>
              </select>
            </Field>

            {/* Password — auto-generated, shown in plain text, editable */}
            <div className="col-span-2">
              <div className="flex items-center justify-between mb-1">
                <label className="block text-sm font-medium text-gray-700">
                  Password
                  {isAutoGenerated && (
                    <span className="ml-2 text-[10px] font-normal text-blue-600 bg-blue-50 px-1.5 py-0.5 rounded-full">
                      Auto-generated
                    </span>
                  )}
                </label>
                <div className="flex items-center gap-3 text-xs">
                  {passwordOverridden && (
                    <button type="button" onClick={resetPassword}
                      className="text-blue-600 hover:underline">
                      Reset to auto
                    </button>
                  )}
                  <button type="button" onClick={() => setShowPassword((v) => !v)}
                    className="text-slate-500 hover:text-slate-700">
                    {showPassword ? 'Hide' : 'Show'}
                  </button>
                </div>
              </div>
              <div className="relative">
                <input
                  required
                  type={showPassword ? 'text' : 'password'}
                  value={form.password}
                  onChange={(e) => handlePasswordChange(e.target.value)}
                  className={`${input(fieldError('password'))} pr-10 font-mono`}
                  placeholder="Fill name & DOB to auto-generate"
                />
              </div>
              {fieldError('password') && <p className="text-xs text-red-600 mt-1">{fieldError('password')}</p>}
              {isAutoGenerated && (
                <p className="text-xs text-slate-500 mt-1">
                  Format: first 4 letters of first name + date of birth (ddmmyyyy). e.g. Aman + 04/02/2001 → Aman04022001
                </p>
              )}
            </div>
          </div>
        </section>

        {/* Profile */}
        <section>
          <h3 className="text-sm font-semibold text-gray-700 mb-3 pb-1 border-b border-gray-100">Profile</h3>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Blood Group" error={fieldError('blood_group')}>
              <select value={form.blood_group} onChange={(e) => set('blood_group', e.target.value)} className={input(fieldError('blood_group'))}>
                <option value="">Select</option>
                {['A+','A-','B+','B-','AB+','AB-','O+','O-'].map((b) => (
                  <option key={b} value={b}>{b}</option>
                ))}
              </select>
            </Field>
            <Field label="Address" error={fieldError('address')} className="col-span-2">
              <textarea rows={2} value={form.address} onChange={(e) => set('address', e.target.value)}
                className={input(fieldError('address'))} placeholder="Home address" />
            </Field>
          </div>
        </section>

        {/* Guardian */}
        <section>
          <h3 className="text-sm font-semibold text-gray-700 mb-3 pb-1 border-b border-gray-100">Guardian</h3>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Guardian Name" error={fieldError('guardian_name')}>
              <input value={form.guardian_name} onChange={(e) => set('guardian_name', e.target.value)}
                className={input(fieldError('guardian_name'))} placeholder="Parent / Guardian name" />
            </Field>
            <Field label="Guardian Phone" error={fieldError('guardian_phone')}>
              <input value={form.guardian_phone} onChange={(e) => set('guardian_phone', e.target.value)}
                className={input(fieldError('guardian_phone'))} placeholder="+91 9876543210" />
            </Field>
          </div>
        </section>

        <div className="flex justify-end gap-2 pt-2">
          <button type="button" onClick={() => navigate('/admin/students')}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200">
            Cancel
          </button>
          <button type="submit" disabled={createMut.isPending}
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50">
            {createMut.isPending ? 'Creating...' : 'Create Student'}
          </button>
        </div>
      </form>
    </div>
  )
}

function Field({ label, error, children, className = '' }) {
  return (
    <div className={className}>
      <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
      {children}
      {error && <p className="text-xs text-red-600 mt-1">{error}</p>}
    </div>
  )
}

function input(hasError) {
  return `w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 ${
    hasError ? 'border-red-400' : 'border-gray-300'
  }`
}
