import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { createStudent } from '@/api/students'
import PageHeader from '@/components/ui/PageHeader'

const EMPTY = {
  email: '', first_name: '', last_name: '', phone: '', password: '',
  date_of_birth: '', gender: '',
  blood_group: '', address: '',
  father_name: '', father_occupation: '', father_salary_range: '',
  mother_name: '', mother_occupation: '', mother_salary_range: '',
  guardian_name: '', guardian_phone: '', guardian_relation: '',
}

function buildPassword(firstName, dob) {
  const name = firstName.trim().slice(0, 4)
  if (!name || !dob) return ''
  const [y, m, d] = dob.split('-')
  if (!y || !m || !d) return ''
  return `${name}${d}${m}${y}`
}

export default function StudentForm() {
  const navigate = useNavigate()
  const qc = useQueryClient()
  const [form, setForm] = useState(EMPTY)
  const [errors, setErrors] = useState({})
  const [passwordOverridden, setPasswordOverridden] = useState(false)
  const [showPassword, setShowPassword] = useState(true)

  const createMut = useMutation({
    mutationFn: createStudent,
    onSuccess: (res) => {
      qc.invalidateQueries({ queryKey: ['students'] })
      navigate(`/admin/students/${res.data.id}`)
    },
    onError: (e) => {
      const data = e.response?.data
      if (data && typeof data === 'object') setErrors(data)
      else setErrors({ non_field_errors: ['Something went wrong.'] })
    },
  })

  function set(field, value) {
    setForm((f) => {
      const next = { ...f, [field]: value }
      if (!passwordOverridden && (field === 'first_name' || field === 'date_of_birth')) {
        next.password = buildPassword(
          field === 'first_name' ? value : f.first_name,
          field === 'date_of_birth' ? value : f.date_of_birth,
        )
      }
      return next
    })
    setErrors((e) => { const next = { ...e }; delete next[field]; return next })
  }

  function handlePasswordChange(value) {
    setPasswordOverridden(true)
    setForm((f) => ({ ...f, password: value }))
    setErrors((e) => { const next = { ...e }; delete next.password; return next })
  }

  function resetPassword() {
    setPasswordOverridden(false)
    setForm((f) => ({ ...f, password: buildPassword(f.first_name, f.date_of_birth) }))
  }

  function handleSubmit(e) {
    e.preventDefault()
    setErrors({})
    createMut.mutate(form)
  }

  const fe = (f) => errors[f]?.[0] ?? errors[f]
  const isAutoGenerated = !passwordOverridden && !!form.password

  return (
    <div>
      <PageHeader title="Add New Student" subtitle="Creates a student account and profile" />

      <form onSubmit={handleSubmit} className="bg-white rounded-xl border border-gray-200 p-6 max-w-2xl space-y-6">
        {errors.non_field_errors && (
          <p className="text-sm text-red-600">{errors.non_field_errors[0]}</p>
        )}

        {/* Account */}
        <section>
          <h3 className="text-sm font-semibold text-gray-700 mb-3 pb-1 border-b border-gray-100">Account</h3>
          <div className="grid grid-cols-2 gap-4">
            <Field label="First Name" error={fe('first_name')}>
              <input required value={form.first_name} onChange={(e) => set('first_name', e.target.value)}
                className={inp(fe('first_name'))} placeholder="Jane" />
            </Field>
            <Field label="Last Name" error={fe('last_name')}>
              <input required value={form.last_name} onChange={(e) => set('last_name', e.target.value)}
                className={inp(fe('last_name'))} placeholder="Doe" />
            </Field>
            <Field label="Email" error={fe('email')}>
              <input required type="email" value={form.email} onChange={(e) => set('email', e.target.value)}
                className={inp(fe('email'))} placeholder="jane@school.com" />
            </Field>
            <Field label="Phone" error={fe('phone')}>
              <input required value={form.phone} onChange={(e) => set('phone', e.target.value)}
                className={inp(fe('phone'))} placeholder="+91 9876543210" />
            </Field>
            <Field label="Date of Birth" error={fe('date_of_birth')}>
              <input required type="date" value={form.date_of_birth} onChange={(e) => set('date_of_birth', e.target.value)}
                className={inp(fe('date_of_birth'))} />
            </Field>
            <Field label="Gender" error={fe('gender')}>
              <select required value={form.gender} onChange={(e) => set('gender', e.target.value)} className={inp(fe('gender'))}>
                <option value="">Select</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
                <option value="other">Other</option>
              </select>
            </Field>

            {/* Password — auto-generated */}
            <div className="col-span-2">
              <div className="flex items-center justify-between mb-1">
                <label className="block text-sm font-medium text-gray-700">
                  Password
                  {isAutoGenerated && (
                    <span className="ml-2 text-[10px] font-normal text-blue-600 bg-blue-50 px-1.5 py-0.5 rounded-full">
                      Auto-generated
                    </span>
                  )}
                </label>
                <div className="flex items-center gap-3 text-xs">
                  {passwordOverridden && (
                    <button type="button" onClick={resetPassword} className="text-blue-600 hover:underline">
                      Reset to auto
                    </button>
                  )}
                  <button type="button" onClick={() => setShowPassword((v) => !v)}
                    className="text-slate-500 hover:text-slate-700">
                    {showPassword ? 'Hide' : 'Show'}
                  </button>
                </div>
              </div>
              <input
                required
                type={showPassword ? 'text' : 'password'}
                value={form.password}
                onChange={(e) => handlePasswordChange(e.target.value)}
                className={`${inp(fe('password'))} font-mono`}
                placeholder="Fill name & DOB to auto-generate"
              />
              {fe('password') && <p className="text-xs text-red-600 mt-1">{fe('password')}</p>}
              {isAutoGenerated && (
                <p className="text-xs text-slate-500 mt-1">
                  Format: first 4 letters of first name + date of birth (ddmmyyyy). e.g. Aman + 04/02/2001 → Aman04022001
                </p>
              )}
            </div>
          </div>
        </section>

        {/* Profile */}
        <section>
          <h3 className="text-sm font-semibold text-gray-700 mb-3 pb-1 border-b border-gray-100">Profile</h3>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Blood Group" error={fe('blood_group')}>
              <select required value={form.blood_group} onChange={(e) => set('blood_group', e.target.value)} className={inp(fe('blood_group'))}>
                <option value="">Select</option>
                {['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map((b) => (
                  <option key={b} value={b}>{b}</option>
                ))}
              </select>
            </Field>
            <Field label="Address" error={fe('address')} className="col-span-2">
              <textarea required rows={2} value={form.address} onChange={(e) => set('address', e.target.value)}
                className={inp(fe('address'))} placeholder="Home address" />
            </Field>
          </div>
        </section>

        {/* Parents */}
        <section>
          <h3 className="text-sm font-semibold text-gray-700 mb-3 pb-1 border-b border-gray-100">Parents</h3>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Father's Name" error={fe('father_name')}>
              <input required value={form.father_name} onChange={(e) => set('father_name', e.target.value)}
                className={inp(fe('father_name'))} placeholder="Father's full name" />
            </Field>
            <Field label="Father's Occupation" error={fe('father_occupation')}>
              <input required value={form.father_occupation} onChange={(e) => set('father_occupation', e.target.value)}
                className={inp(fe('father_occupation'))} placeholder="e.g. Engineer, Farmer" />
            </Field>
            <Field label="Father's Salary Range" error={fe('father_salary_range')} className="col-span-2">
              <select required value={form.father_salary_range} onChange={(e) => set('father_salary_range', e.target.value)}
                className={inp(fe('father_salary_range'))}>
                <option value="">Select range</option>
                <option value="₹0">₹0 (No Income)</option>
                <option value="Below ₹1L">Below ₹1L / year</option>
                <option value="₹1L–3L">₹1L – 3L / year</option>
                <option value="₹3L–5L">₹3L – 5L / year</option>
                <option value="₹5L–10L">₹5L – 10L / year</option>
                <option value="₹10L–20L">₹10L – 20L / year</option>
                <option value="Above ₹20L">Above ₹20L / year</option>
              </select>
            </Field>

            <Field label="Mother's Name" error={fe('mother_name')}>
              <input required value={form.mother_name} onChange={(e) => set('mother_name', e.target.value)}
                className={inp(fe('mother_name'))} placeholder="Mother's full name" />
            </Field>
            <Field label="Mother's Occupation" error={fe('mother_occupation')}>
              <input required value={form.mother_occupation} onChange={(e) => set('mother_occupation', e.target.value)}
                className={inp(fe('mother_occupation'))} placeholder="e.g. Teacher, Homemaker" />
            </Field>
            <Field label="Mother's Salary Range" error={fe('mother_salary_range')} className="col-span-2">
              <select required value={form.mother_salary_range} onChange={(e) => set('mother_salary_range', e.target.value)}
                className={inp(fe('mother_salary_range'))}>
                <option value="">Select range</option>
                <option value="₹0">₹0 (No Income)</option>
                <option value="Below ₹1L">Below ₹1L / year</option>
                <option value="₹1L–3L">₹1L – 3L / year</option>
                <option value="₹3L–5L">₹3L – 5L / year</option>
                <option value="₹5L–10L">₹5L – 10L / year</option>
                <option value="₹10L–20L">₹10L – 20L / year</option>
                <option value="Above ₹20L">Above ₹20L / year</option>
              </select>
            </Field>
          </div>
        </section>

        {/* Guardian */}
        <section>
          <h3 className="text-sm font-semibold text-gray-700 mb-3 pb-1 border-b border-gray-100">Guardian</h3>
          <div className="grid grid-cols-2 gap-4">
            <Field label="Guardian Name" error={fe('guardian_name')}>
              <input required value={form.guardian_name} onChange={(e) => set('guardian_name', e.target.value)}
                className={inp(fe('guardian_name'))} placeholder="Guardian full name" />
            </Field>
            <Field label="Relation to Student" error={fe('guardian_relation')}>
              <select required value={form.guardian_relation} onChange={(e) => set('guardian_relation', e.target.value)}
                className={inp(fe('guardian_relation'))}>
                <option value="">Select relation</option>
                <option value="Father">Father</option>
                <option value="Mother">Mother</option>
                <option value="Grandfather">Grandfather</option>
                <option value="Grandmother">Grandmother</option>
                <option value="Uncle">Uncle</option>
                <option value="Aunt">Aunt</option>
                <option value="Elder Sibling">Elder Sibling</option>
                <option value="Other">Other</option>
              </select>
            </Field>
            <Field label="Guardian Phone" error={fe('guardian_phone')} className="col-span-2">
              <input required value={form.guardian_phone} onChange={(e) => set('guardian_phone', e.target.value)}
                className={inp(fe('guardian_phone'))} placeholder="+91 9876543210" />
            </Field>
          </div>
        </section>

        <div className="flex justify-end gap-2 pt-2">
          <button type="button" onClick={() => navigate('/admin/students')}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200">
            Cancel
          </button>
          <button type="submit" disabled={createMut.isPending}
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-50">
            {createMut.isPending ? 'Creating...' : 'Create Student'}
          </button>
        </div>
      </form>
    </div>
  )
}

function Field({ label, error, children, className = '' }) {
  return (
    <div className={className}>
      <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
      {children}
      {error && <p className="text-xs text-red-600 mt-1">{error}</p>}
    </div>
  )
}

function inp(hasError) {
  return `w-full border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 ${
    hasError ? 'border-red-400' : 'border-gray-300'
  }`
}
