# Generated by Django 4.2.30 on 2026-05-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_parent_guardian_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_salary_range',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
