# Generated by Django 4.2.30 on 2026-05-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_studentapplication_father_occupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='guardian_occupation',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='guardian_salary_range',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_occupation',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='guardian_salary_range',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='father_salary_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='mother_salary_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_salary_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_salary_range',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
